spring.application.name=deliverytask

spring.datasource.url=jdbc:h2:file:./database/delivery_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
weather.import.cron=0 15 * * * *

logging.level.ee.fujitsu.deliverytask=DEBUG
logging.level.org.springframework.web=INFO